FROM openjdk:latest                                                                                                                                                                                                     
ADD /var/jenkins_home/workspace/build-pc/target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar ~/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar

EXPOSE 8080

CMD ["java","-jar","~/spring-petclinic-2.2.0.39.BUILD-SNAPSHOT.jar"]
