version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins_docker_file.dockerfile
    image: 'jenkins/jenkins:lts'
    restart: always
    privileged: true
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/home/jenkins
  registry:
    restart: always
    image: 'registry'
    container_name: registry_v2
    ports:
      - 5000:5000
    volumes:
      - repo:/var/lib/registry
volumes:
  jenkins_data:
    driver: local
  repo:
    driver: local
