version: '3'
services:
  petclinic:
    build:
      context: .
    image: '10.23.27.6:443/petclinic:stable' 
    restart: always
    ports:
      - 5555:8080
    volumes:
      - petclinic_data:/home/vagrant/pet
volumes:
  petclinic_data:
    driver: local
