version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins_docker_file.dockerfile
    image: 'jenkins/jenkins:lts'
    restart: always
    privileged: true
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/home/jenkins
  registry:
    restart: always
    image: 'registry:2'
    container_name: registry_v2
    ports:
      #- 5000:5000
      - 443:443
    environment:
#      - REGISTRY_AUTH=htpasswd
#      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
#      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    volumes:
      - /certs:/certs
      - /registry:/var/lib/registry
      - /auth:/auth
      #- repo:/var/lib/registry
#volumes:
#  jenkins_data:
#    driver: local
#  repo:
#    driver: local
